"""Category model for discovery item classification."""

from datetime import datetime
from enum import Enum as PyEnum
from typing import Optional
from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Enum
from sqlalchemy.orm import relationship
from app.core.database import Base


class CategoryType(str, PyEnum):
    """Category type enumeration."""

    AUTO_GENERATED = "AUTO_GENERATED"  # Generated by AI/ML systems
    MANUAL = "MANUAL"                  # Manually created by users
    CASE_SPECIFIC = "CASE_SPECIFIC"    # Created for specific case needs


class Category(Base):
    """
    Category model for classifying discovery items.

    Categories can be auto-generated through AI classification, manually created,
    or case-specific. They support hierarchical organization through parent-child
    relationships.
    """

    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String(255), nullable=False, unique=True, index=True)
    type = Column(
        Enum(CategoryType, native_enum=True, create_constraint=True),
        nullable=False,
        index=True
    )
    parent_category_id = Column(
        Integer,
        ForeignKey("categories.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Relationships
    parent_category = relationship(
        "Category",
        remote_side=[id],
        backref="subcategories"
    )
    discovery_items = relationship(
        "DiscoveryItem",
        secondary="discovery_item_categories",
        back_populates="categories"
    )

    def __repr__(self) -> str:
        return f"<Category(id={self.id}, name='{self.name}', type='{self.type.value}')>"
