[project]
name = "legalease-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "celery>=5.5.3",
    "docxtpl>=0.20.1",
    "fastapi>=0.118.2",
    "httpx>=0.28.1",
    "minio>=7.2.18",
    "numpy>=1.26.0",
    "pdf2image>=1.17.0",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "pymupdf>=1.25.3",
    "pypdf>=5.1.0",
    "pytesseract>=0.3.13",
    "python-docx>=1.1.2",
    "python-multipart>=0.0.20",
    "qdrant-client>=1.15.1",
    "redis>=6.4.0",
    "sentence-transformers>=5.1.1",
    "spacy>=3.8.7",
    "sqlalchemy>=2.0.43",
    "tiktoken>=0.12.0",
    "torch>=2.0.0",
    "transformers>=4.57.0",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.0",
]
