"""add_transcript_highlights

Revision ID: b156ff2242c8
Revises: f7g8h9i0j1k2
Create Date: 2025-10-17 02:26:41.639840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b156ff2242c8'
down_revision: Union[str, Sequence[str], None] = 'f7g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_batches_case_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_source_type'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_visual_content_discovery_item_id'), table_name='visual_content')
    op.drop_index(op.f('ix_visual_content_id'), table_name='visual_content')
    op.drop_table('visual_content')
    op.drop_index(op.f('ix_discovery_item_categories_auto_generated'), table_name='discovery_item_categories')
    op.drop_index(op.f('ix_discovery_item_categories_category_id'), table_name='discovery_item_categories')
    op.drop_index(op.f('ix_discovery_item_categories_discovery_item_id'), table_name='discovery_item_categories')
    op.drop_table('discovery_item_categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_video_summaries_discovery_item_id'), table_name='video_summaries')
    op.drop_index(op.f('ix_video_summaries_id'), table_name='video_summaries')
    op.drop_index(op.f('ix_video_summaries_importance_score'), table_name='video_summaries')
    op.drop_table('video_summaries')
    op.drop_index(op.f('ix_discovery_items_case_id'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_form_factor'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_id'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_importance_score'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_processed'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_source'), table_name='discovery_items')
    op.drop_index(op.f('ix_discovery_items_type'), table_name='discovery_items')
    op.drop_table('discovery_items')
    op.drop_index(op.f('ix_email_messages_discovery_item_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sender'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_subject'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_timestamp'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_social_media_posts_author'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_discovery_item_id'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_id'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_platform'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_post_timestamp'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_thread_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')
    op.drop_index(op.f('ix_call_logs_associated_audio_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_type'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_caller'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_discovery_item_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_recipient'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_timestamp'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_constraint(op.f('cases_case_number_key'), 'cases', type_='unique')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.add_column('transcript_segments', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('transcriptions_document_id_key'), 'transcriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('transcriptions_document_id_key'), 'transcriptions', ['document_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('transcript_segments', 'highlights')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=False)
    op.create_unique_constraint(op.f('cases_case_number_key'), 'cases', ['case_number'], postgresql_nulls_not_distinct=False)
    op.create_table('call_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('caller', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('call_type', postgresql.ENUM('INCOMING', 'OUTGOING', 'MISSED', 'VOICEMAIL', name='calltype'), autoincrement=False, nullable=False),
    sa.Column('associated_audio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['associated_audio_id'], ['discovery_items.id'], name=op.f('call_logs_associated_audio_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('call_logs_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('call_logs_pkey')),
    sa.UniqueConstraint('discovery_item_id', name=op.f('call_logs_discovery_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_call_logs_timestamp'), 'call_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_call_logs_recipient'), 'call_logs', ['recipient'], unique=False)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_discovery_item_id'), 'call_logs', ['discovery_item_id'], unique=True)
    op.create_index(op.f('ix_call_logs_caller'), 'call_logs', ['caller'], unique=False)
    op.create_index(op.f('ix_call_logs_call_type'), 'call_logs', ['call_type'], unique=False)
    op.create_index(op.f('ix_call_logs_associated_audio_id'), 'call_logs', ['associated_audio_id'], unique=False)
    op.create_table('social_media_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('post_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('engagement_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('social_media_posts_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('social_media_posts_pkey')),
    sa.UniqueConstraint('discovery_item_id', name=op.f('social_media_posts_discovery_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_social_media_posts_thread_id'), 'social_media_posts', ['thread_id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_post_timestamp'), 'social_media_posts', ['post_timestamp'], unique=False)
    op.create_index(op.f('ix_social_media_posts_platform'), 'social_media_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_media_posts_id'), 'social_media_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_discovery_item_id'), 'social_media_posts', ['discovery_item_id'], unique=True)
    op.create_index(op.f('ix_social_media_posts_author'), 'social_media_posts', ['author'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('email_messages_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_messages_pkey')),
    sa.UniqueConstraint('discovery_item_id', name=op.f('email_messages_discovery_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_email_messages_timestamp'), 'email_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_subject'), 'email_messages', ['subject'], unique=False)
    op.create_index(op.f('ix_email_messages_sender'), 'email_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_discovery_item_id'), 'email_messages', ['discovery_item_id'], unique=True)
    op.create_table('discovery_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('discovery_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PHOTO', 'VIDEO', 'AUDIO', 'SOCIAL_POST', 'EMAIL', 'CALL_LOG', 'SMS', name='discoveryitemtype'), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('CELLEBRITE', 'PROSECUTOR', 'EVIDENCE', 'SURVEILLANCE', 'BODY_CAM', name='discoveryitemsource'), autoincrement=False, nullable=False),
    sa.Column('form_factor', postgresql.ENUM('SHORT_FORM', 'LONG_FORM', 'SINGLE_ITEM', name='discoveryitemformfactor'), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('importance_score IS NULL OR importance_score >= 0.0::double precision AND importance_score <= 1.0::double precision', name='check_importance_score_range'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='discovery_items_case_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='discovery_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_discovery_items_type'), 'discovery_items', ['type'], unique=False)
    op.create_index(op.f('ix_discovery_items_source'), 'discovery_items', ['source'], unique=False)
    op.create_index(op.f('ix_discovery_items_processed'), 'discovery_items', ['processed'], unique=False)
    op.create_index(op.f('ix_discovery_items_importance_score'), 'discovery_items', ['importance_score'], unique=False)
    op.create_index(op.f('ix_discovery_items_id'), 'discovery_items', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_items_form_factor'), 'discovery_items', ['form_factor'], unique=False)
    op.create_index(op.f('ix_discovery_items_case_id'), 'discovery_items', ['case_id'], unique=False)
    op.create_table('video_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comprehensive_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_moments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('visual_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flagged_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('importance_score IS NULL OR importance_score >= 0.0::double precision AND importance_score <= 1.0::double precision', name=op.f('check_video_importance_score_range')),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('video_summaries_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_summaries_pkey')),
    sa.UniqueConstraint('discovery_item_id', name=op.f('video_summaries_discovery_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_video_summaries_importance_score'), 'video_summaries', ['importance_score'], unique=False)
    op.create_index(op.f('ix_video_summaries_id'), 'video_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_video_summaries_discovery_item_id'), 'video_summaries', ['discovery_item_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('AUTO_GENERATED', 'MANUAL', 'CASE_SPECIFIC', name='categorytype'), autoincrement=False, nullable=False),
    sa.Column('parent_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name='categories_parent_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('discovery_item_categories',
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('auto_generated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score >= 0.0::double precision AND confidence_score <= 1.0::double precision', name=op.f('check_category_confidence_score_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('discovery_item_categories_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('discovery_item_categories_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discovery_item_id', 'category_id', name=op.f('discovery_item_categories_pkey'))
    )
    op.create_index(op.f('ix_discovery_item_categories_discovery_item_id'), 'discovery_item_categories', ['discovery_item_id'], unique=False)
    op.create_index(op.f('ix_discovery_item_categories_category_id'), 'discovery_item_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_discovery_item_categories_auto_generated'), 'discovery_item_categories', ['auto_generated'], unique=False)
    op.create_table('visual_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discovery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frame_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp_in_video', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vlm_caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_objects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detected_scenes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detected_activities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sensitive_flags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_meme', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discovery_item_id'], ['discovery_items.id'], name=op.f('visual_content_discovery_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('visual_content_pkey'))
    )
    op.create_index(op.f('ix_visual_content_id'), 'visual_content', ['id'], unique=False)
    op.create_index(op.f('ix_visual_content_discovery_item_id'), 'visual_content', ['discovery_item_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('processed_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importstatus'), server_default=sa.text("'PENDING'::importstatus"), autoincrement=False, nullable=False),
    sa.Column('import_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('import_batches_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('import_batches_pkey'))
    )
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_import_batches_source_type'), 'import_batches', ['source_type'], unique=False)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_case_id'), 'import_batches', ['case_id'], unique=False)
    # ### end Alembic commands ###
