http:
  middlewares:
    default-headers:
      headers:
        frameDeny: false
        customFrameOptionsValue: "SAMEORIGIN"
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "geolocation=()"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
          - X-CSRF-Token
          - X-Requested-With
        accessControlAllowOriginList:
          - http://app.localhost
          - https://app.localhost
          - http://api.localhost
          - https://api.localhost
          - http://auth.localhost
          - https://auth.localhost
    keycloak-headers:
      headers:
        frameDeny: false
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
tls:
  certificates: []
